# Generated by Django 4.2.14 on 2024-07-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('tags', models.CharField(max_length=150)),
                ('source', models.TextField()),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
                'ordering': ['-id'],
            },
        ),
    ]
