# Generated by Django 4.2.14 on 2024-07-26 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0002_news_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('ECONOMIC', 'Economic'), ('SOCIAL', 'Social'), ('CULTURAL', 'Cultural'), ('SPORTS', 'Sports'), ('POLITICAL', 'Political'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
